# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09e59b03ee7ec5bdb9260c9bf19d6f95"
name = "Product Stock Alert"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "inventory_levels/update" ]
uri = "/webhooks/inventory_levels_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
